### ISSUE TITLE
[FR] Autogenerate custom domain watchlist rule

### ISSUE THREAD

**Issue by rw-access** [elastic/detection-rules#1049]
**Is your feature request related to a problem? Please describe.**
@bfilar had an idea. What if we used [dnstwist](https://github.com/elceef/dnstwist) or something similar to autogenerate a rule using the CLI? Then you can find spoofing attacks on domains that you want to protect.

**Describe the solution you'd like**
 The thought is that you can tell this command all of the domains that you want to watch. It runs them through DNS twist and generates a list of domains to watch.

We can autogenerate rules using the EQL or KQL syntax trees. They handle escaping and everything and can go from python into the target language.  So you can convert a python dictionary into KQL code.

There are a few different ways to do this via the CLI. But in the end, we should have a TOML file prepopulated with all of the right fields.

**Comment by threat-punter** [comment]
@ajosh0504 and I are going to look at this. We met today and our initial thoughts are to add a `dnstwist` command to the detection-rules CLI with the following options and arguments:

- `path` - Path to dnstwist's output in csv or other format
- `create-rule` - Generate the rule and upload it to Kibana. This seems like a good use case for an [Indicator Match](https://www.elastic.co/guide/en/security/current/rules-ui-create.html#create-indicator-rule) rule
- `index` - Index the dnstwist dataset in Elasticsearch
  - Some users might be interested in a dashboard of activity for hunting/baselining purposes in addition to/instead of the detection rule
  - We can create Kibana visualizations and a dashboard for users to import to show things like the number of domains in the list, a list and count of endpoints communicating to any of the domains, a count of events by domain and by endpoint, etc
  - The visualizations and dashboards will need to look at the latest indexed dnstwist data when the user uses the `index` option again

We can ask the user to import the visualizations and dashboards via the Kibana UI or provide that functionality in the CLI.

**Comment by ajosh0504** [comment]
Since the dashboard needs to be a one-time upload only, we could probably keep it out of the CLI and provide instructions to import it instead. When they run an update, they can adjust the dashboard query in Kibana to reflect the update date. 

Alternatively, we  can delete and recreate the index each time the user runs the `index` option to only reflect data from the latest `dnstwist` run. That way the index and dashboards will always reflect only the updated data.

Wdyt @threat-punter ?

**Comment by threat-punter** [comment]
I think deleting documents from the `dnstwist` index and indexing the new dataset is fine and the most straightforward approach unless we/users want to do any comparisons between the datasets. I think we can plan on replacing the index each time for now. 👍

**Comment by threat-punter** [comment]
@ajosh0504 for our reference, we can potentially create a threat match rule similar to what @peasead did [here](https://github.com/elastic/detection-rules/pull/1133/files#diff-129eed33aa159d4a761fbe81fdefb932d995ed8ae0540450298f525f8e3fd5d9R38-R46).

**Comment by ajosh0504** [comment]
@threat-punter Sounds good. For my own reference, what's the difference between threat match rules and general detection rules?

**Comment by threat-punter** [comment]
@ajosh0504 I'll get a branch going for this next week and let you know when the bare bones are there.

Re your above question about detection rule types:

> - Custom query: Query-based rule, which searches the defined indices and creates an alert when a document matches the rule’s query
> - Indicator match: Creates an alert when Elastic Security index field values match field values defined in the specified indicator index patterns. For example, you can create an indicator index for IP addresses and use this index to create an alert whenever an event’s destination.ip equals a value in the index.

Source: https://www.elastic.co/guide/en/security/master/rules-ui-create.html

**Comment by ajosh0504** [comment]
@threat-punter @brokensound77 When do we think we can complete this? [This](https://github.com/elastic/security-team/issues/1420) could benefit from the work we've done here.

**Comment by threat-punter** [comment]
@ajosh0504 I'm still seeing errors when I attempt the final step (uploading the rule to Kibana) using `ctx.invoke(upload_rule, rule_file=[custom_rule_file])`.

Unfortunately, I'm not going to be able to work on this in the near term due to other priorities.

**Comment by ajosh0504** [comment]
@threat-punter No problem! @brokensound77 Is there anything I can do here to get this across the finish line? The issue I linked above is partly my responsibility for 7.15 so I should have some time to spare for this.

**Comment by brokensound77** [comment]
I am looking at this now and will let you know
