### ISSUE TITLE
[Rule Tuning] [Okta] High Number of Okta User Password Reset or Unlock Attempts

### ISSUE THREAD

**Issue by BenB196** [elastic/detection-rules#1172]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/okta/defense_evasion_suspicious_okta_user_password_reset_or_unlock_attempts.toml

## Description
The above rule uses the wrong field for the threshold metric. Currently the threshold metric is ```okta.actor.id```, however, this value can sometimes be ```Okta System```. This results in two issues:

1. The rule can be triggered more frequently than intended, as ```Okta System``` can interact with multiple accounts within the time frame.
2. The alert doesn't contain any real useful information, as its been triggered off of the ```Okta System``` account, requiring additional investigation on the matter.

A third issue that is more about ```okta.actor.id``` in general:

3. ```okta.actor.id```  is just a random string, and doesn't provide any quick (at a glance) info, on who the user is, resulting in additional digging to find out if this is valid.

## Example Data

I think it would make more sense to use the threshold based off of something like okta.target.alternate_id as it solves the above problems. (One thing I'm not 100% sure on is whether this field is present during all events).

Example (truncated and snipped) event where okta.actor.id is of ```Okta System```

```
{
  "fields": {
    "okta.client.device": [
      "Mobile"
    ],
    "okta.client.ip": [
      "<snipped>"
    ],
    "service.type": [
      "okta"
    ],
    "okta.security_context.as.number": [
      <snipped>
    ],
    "user.full_name.text": [
      "Okta System"
    ],
    "event.outcome": [
      "success"
    ],
    "okta.uuid": [
      "<snipped>"
    ],
    "source.user.full_name.text": [
      "Okta System"
    ],
    "fileset.name": [
      "system"
    ],
    "input.type": [
      "httpjson"
    ],
    "okta.authentication_context.authentication_step": [
      0
    ],
    "related.user": [
      "Okta System"
    ],
    "okta.client.zone": [
      "null"
    ],
    "okta.target.type": [
      "User",
      "MobilePhone"
    ],
    "okta.authentication_context.external_session_id": [
      "unknown"
    ],
    "okta.security_context.is_proxy": [
      false
    ],
    "okta.actor.type": [
      "SystemPrincipal"
    ],
    "okta.debug_context.debug_data.url": [
      "/api/v1/authn/recovery/password?"
    ],
    "okta.actor.display_name": [
      "Okta System"
    ],
    "event.action": [
      "system.sms.send_password_reset_message"
    ],
    "okta.security_context.isp": [
      "<snipped>"
    ],
    "okta.outcome.result": [
      "SUCCESS"
    ],
    "okta.debug_context.debug_data.request_uri": [
      "/api/v1/authn/recovery/password"
    ],
    "okta.display_message": [
      "Send self-service password reset SMS message"
    ],
    "client.user.full_name": [
      "Okta System"
    ],
    "okta.target.id": [
      "<snipped (real user)>",
      "<snipped (real user)>"
    ],
    "okta.actor.alternate_id": [
      "system@okta.com"
    ],
    "event.kind": [
      "event"
    ],
    "client.user.id": [
      "<snipped>"
    ],
    "okta.security_context.domain": [
      "<snipped>"
    ],
    "okta.client.user_agent.browser": [
      "<snipped>"
    ],
    "okta.transaction.id": [
      "<snipped>"
    ],
    "ecs.version": [
      "1.8.0"
    ],
    "okta.target.display_name": [
      "<snipped> (real user)",
      "<snipped> (real user)"
    ],
    "user.full_name": [
      "Okta System"
    ],
    "agent.version": [
      "7.12.1"
    ],
    "okta.debug_context.debug_data.request_id": [
      "<snipped>"
    ],
    "source.user.full_name": [
      "Okta System"
    ],
    "okta.target.alternate_id": [
      "<snipped> (real user)",
      "<snipped> (real user)"
    ],
    "okta.event_type": [
      "system.sms.send_password_reset_message"
    ],
    "okta.debug_context.debug_data.threat_suspected": [
      "false"
    ],
    "okta.transaction.type": [
      "WEB"
    ],
    "event.module": [
      "okta"
    ],
    "okta.actor.id": [
      "<snipped> (okta system)"
    ],
    "source.user.id": [
      "<snipped> (okta system)"
    ],
    "client.user.full_name.text": [
      "Okta System"
    ],
    "okta.security_context.as.organization.name": [
      "<snipped>"
    ],
    "event.dataset": [
      "okta.system"
    ]
  }
}
```

**Comment by austinsonger** [comment]
This rule is layout this way on purpose. Because there will be some users and organizations that would want to be notified when `Okta System` triggers it.

If you read the false positives in the rule, it states:

> To fit this rule to their organization, users can duplicate this rule and edit the schedule and threshold values in 
the new rule.

So with that advice, you could duplicate the rule and then excludes `Okta System` account, which will help your issue with false positive. This rule is obviously develop to catch alot by default, but can be tweak to the meet the needs of the user or organization.

But to be honest, what do you considered a "High" number? that is subjective.

so I feel like this rule could benefit of turning into a ML Rule down the road @bm11100 


-------------------

@BenB196 Here is  some other Okta API data information that you can use to improve the rule for your use case.

#### Event API to System Log API  

| Event Property               | Log Property                                      |
| ---------------------------- | ------------------------------------------------- |
| event.eventId                | log.uuid                                          |
| event.sessionId              | log.authenticationContext.externalSessionId       |
| event.requestId              | log.transaction.id                                |
| event.published              | log.published                                     |
| event.action.categories[0]   | n/a, log.severity and log.outcome contain similar |
| event.action.categories[1]   | n/a, log.severity and log.outcome contain similar |
| event.action.objectType      | log.legacyEventType                               |
| event.action.requestUri      | log.debugContext.debugData.requestUri             |
| event.actors[0].id           | log.client.userAgent.rawUserAgent                 |
| event.actors[0].displayName  | log.client.userAgent.browser                      |
| event.actors[0].ipAddress    | log.client.ipAddress                              |
| event.actors[0].objectType   | log.client.device                                 |
| event.targets[0].id          | log.actor.id                                      |
| event.targets[0].displayName | log.actor.displayName                             |
| event.targets[0].login       | log.actor.alternateId                             |
| event.targets[0].objectType  | log.actor.type                                    |
|                              |                                                   |


#### User Events

| EventType Filter                                | Notes                                                   |
| ----------------------------------------------- | ------------------------------------------------------- |
| eventType eq "user.session.start"               | User logging in                                         |
| eventType eq "user.session.end"                 | User logging out                                        |
| eventType eq “policy.evaluate_sign_on”          | Sign in policy evaluation                               |
| eventType eq “user.account.lock”                | Okta user locked out                                    |
| eventType sw "user.authentication.auth"         | All types of Auth events, covering MFA, AD, Radius, etc |
| eventType eq "user.account.update_password"     | User changing password                                  |
| eventType eq "user.authentication.sso"          | User accesing app via single sign on                    |
| eventType eq "user.authentication.auth_via_mfa" | MFA challenge                                           |
| eventType eq "user.mfa.factor.update"           | User changing MFA factors                               |

#### Okta Events

| EventType Filter                               | Notes                                                        |
| ---------------------------------------------- | ------------------------------------------------------------ |
| eventType eq "user.session.access_admin_app    | These events are associated with users accessing the Admin section of your Okta instance |
| eventType eq "user.account.reset_password"     | User password reset by Okta Admin                            |
| eventType eq "zone.update"                     | Modification of a Network Zone                               |
| eventType eq "user.account.privilege.grant"    | Granting Okta Admin to a user                                |
| eventType eq "group.user_membership.add"       | Adding Okta user to a group                                  |
| eventType eq "application.user_membership.add" | Adding user to application membership                        |
| eventType eq "policy.lifecycle.create"         | Creation of a new Okta Policy                                |
| eventType eq ”application.lifecycle.create”    | New Application created                                      |
| eventType eq ”user.lifecycle.activate”         | New Okta user                                                |
| eventType eq "application.provision.user.push" | Assign application to user                                   |
| eventType eq ”user.lifecycle.deactivate”       | Deactivate Okta user                                         |
| eventType eq ”user.lifecycle.suspend”          | Suspend Okta user                                            |
| eventType eq "user.session.clear"              | Okta user login session cleared                              |
| eventType eq "system.api_token.create"         | Creation of a new Okta API token                             |
| eventType eq “system.org.rate_limit.violation” | Hitting the rate limit on requests                           |
| eventType eq “user.mfa.factor.deactivate”      | Removed MFA factor from user                                 |
| eventType eq "user.mfa.factor.reset_all"       | Remove all MFA factors from user                             |

**Comment by BenB196** [comment]
@austinsonger apologies for the delay I was gathering some more data on this before replying.

I think this rule either needs its description updated to be more clear on its goal or should have its aggregated field changed to match its current description.

Reading the current description:

```
Identifies a high number of Okta user password reset or account unlock attempts. An adversary may attempt to obtain unauthorized access to an Okta user account using these methods and attempt to blend in with normal activity in their target's environment and evade detection.
```

The first line is pretty self explanatory. However, when reading the second line: ```access to an Okta user account``` implies (to me) that this rule is specific to a user (group by user), rather than the environment.

However, based of the rule query:

```
event.dataset:okta.system and event.action:(system.email.account_unlock.sent_message or system.email.password_reset.sent_message or system.sms.send_account_unlock_message or system.sms.send_password_reset_message or system.voice.send_account_unlock_call or system.voice.send_password_reset_call or user.account.unlock_token)
```

Over a period, I see roughly 1k events which match this query. Of those events, only 1 contains a real person in the okta.actor.id field. The rest of the events contain ```system@okta.com```. This means that aggregating off ```okta.actor.id``` is effectively just a count of all matching events of the query rather than a count of events grouped by user (which based off of my interpretation of line two of the description it should be)

Looking at all of the events (including the 1 event with a real user as okta.actor.id), they all have the real user as okta.target.alternate_id.

So in my opinion either:

1. The rule description should be changed to:

```
An adversary may attempt to obtain unauthorized access to Okta user accounts using these methods and attempt to blend in with normal activity in their target's environment and evade detection.
```

(I still think okta.actor.id should at least be switched to okta.actor.alternate_id to provide a human readable field)

Or:

2. The aggregate field should be changed to okta.target.alternate_id.
  - In my opinion this would match more closely to the current description.

**Comment by austinsonger** [comment]
@BenB196 Okay I made the change with pull request. 

You can view it here. 
https://github.com/elastic/detection-rules/pull/1200/files

If you give me your name I can make change to authors.

**Comment by BenB196** [comment]
@austinsonger thanks for creating the PR, looks good. My @ works for now as the author.

**Comment by threat-punter** [comment]
I've been tracking your conversation and just wanted to say thanks, @austinsonger and @BenB196 😎
