### ISSUE TITLE
[Rule Tuning]  Rules should be without index hardcoded

### ISSUE THREAD

**Issue by getkub** [elastic/detection-rules#12]
## Description

I've been working in big data tools and ELK for quite some time and when the dataset grows, index names will start growing and custom index names will start to emerge. Hence it is NOT a good idea to hardcode the index in the rules, but should be abstracted out

## Example Data

For example `index = ["auditbeat-*"]` may not be the ONLY index which will contain the unix audit as some of the data will come via syslog and may require a custom `index = ["xyz-audit-*"]` and so on. 

## Suggestion
-  suggestion: is to have a new concept of  `eventtypes` field in rules. This eventtypes will be an abstraction of multiple datasources or indexes or expressions or ecs schema itself 

an example will look like..
```
[rule]
author = ["Elastic"]
description = """
some description
"""
eventtypes = ["linux_auditevents", "skybox_audit", "ecs_schema_audit"]
...
```

the `eventtypes` will be instead of `index` 
and in a new configuration, various datasets should be linked to the eventtypes

**Comment by rw-access** [comment]
Hello!

Since the detection engine is still pretty young, we're not expanding our surface area too quickly. We also can't anticipate every user's configuration, so for now we do have a few things hardcoded.

I think as ECS continues to get more mature and more widely integrated, we'll continue to open things up more. On a similar effort, we're working on making all of the rules use the categorization fields (e.g., `event.category`, `event.type`, etc.). Some of the beats changes are happening in the current release.

I agree that we should strive for our rules to be as independent of data sources as possible. We're still on the way there, so we may be a few releases away.

For now, I would recommend that you use the [workflow to customize and manage these rules](https://www.elastic.co/guide/en/siem/guide/current/rules-ui-create.html#select-all-prebuilt-rules) in your own environment. From there, you can change what indexes every rule is checked against, and you can change the logic when necessary.

Hopefully that helps and provides some more context.

**Comment by getkub** [comment]
Thanks, that make sense.  Only reason why I was saying is, after seeing lot of ELK installations people haven't changed from hardcoded stuff for months/years. So was just giving a suggestion

> I think as ECS continues to get more mature and more widely integrated, we'll continue to open things up more. On a similar effort, we're working on making all of the rules use the categorization fields (e.g., `event.category`, `event.type`, etc.). Some of the beats changes are happening in the current release.
> 
Another thing I've noticed when dataset grows bigger is, the "beats" agent based data collection will reduce as there are plenty of syslog and http requests. So good to keep in mind the data mix will be high ratio of "non-beats" traffic as well, so may be good to have categorisation done nearer to Elasticsearch tier?

**Comment by rw-access** [comment]
Agree on the need to make/keep things flexible. Changes that are configuration-dependent should be well exposed and easy to manage. And there is more to the world of data than just beats. It could be worth it for us to add a tag to track which rules _require_ a specific beat vs which ones are _configured_ to use a specific beat. I'll share this issue further with the rest of the SIEM team, so we can keep flexibility and configuration at the forefront.

>  so may be good to have categorisation done nearer to Elasticsearch tier

I'm not sure what you mean here. Can you share a bit more?
