### ISSUE TITLE
Connection to public DoH server

### ISSUE THREAD

**Issue by termcap** [elastic/detection-rules#1422]
## Description

Browsers now come with DoH enabled by default or users can now enable DoH easily within browsers. Enterprises will lose visibility into DNS queries due to this.

It would be good to have a detection rule that detects queries to public DoH servers. A list can be found here: https://dnscrypt.info/public-servers

### Target indexes

packetbeat-*

### Additional requirements

None

### Target Operating Systems

Any OS

### Platforms

All

**Comment by austinsonger** [comment]
I already have a pull request put in for this.

**Comment by termcap** [comment]
Browser is just one case, it could also be some malware trying to perform DoH. I've seen many machines connecting to the google DNS in my network inspite of the machine DNS being my local DNS server.

Basically, my request is to create a general rule similar to https://www.elastic.co/guide/en/security/current/dns-activity-to-the-internet.html if any connection is made over HTTPS to any public DoH server.

**Comment by austinsonger** [comment]
The main concern I see is that it would be one large detection rule using that list of DoH at around 130 servers and it would be a  be a whack-a-mole detection, because their will be new DoH servers added all the time.

Like I block the list of DoH servers from being able to communicate with any device on my work network as well as disabling the ability of the users from changing their DNS through group policy.

Your best bet is to create your detection rule for your own network and see how it works and then fork the repo and create your pull request (share any logs)  and wait for feedback from the security research engineers.
