### ISSUE TITLE
Feature: use git tags / releases

### ISSUE THREAD

**Issue by hazcod** [elastic/detection-rules#189]
**Is your feature request related to a problem? Please describe.**
At this moment, there is no way to keep track of endpoint rule change unless tracking every commit.

**Describe the solution you'd like**
Use GitHub releases to indicate ruleset upgrades and tag them with versions.

**Comment by rw-access** [comment]
Hello @hazcod!

We have branches for each release. The first release from this repository was 7.9. If you want to see all changes pending for 7.10, then you can compare the `main` branch to the `7.9` branch. This will have more utility over time since all future releases will be fully tracked in this repository. But we didn't retroactively track old releases here.

I'm guessing you want to know the difference between 7.9 and 7.8. For that, you could look at the [prebuilt rule reference](https://www.elastic.co/guide/en/security/current/prebuilt-rules.html).

**Comment by hazcod** [comment]
Hi @rw-access , I see. I was. hoping to be able to subscribe to github releases.

**Comment by rw-access** [comment]
Gotcha. I forget that there's the special watch mode for those. For now, I'm not sure if that process adds much value to our team. If it does in the future, I think this would be a good win.

Also, all of our releases will coincide with Elastic Stack releases. I don't know the best way to subscribe to Elastic releases, but that would be your best bet, unless someone else in @elastic/security-intelligence-analytics has another idea.

**Comment by rw-access** [comment]
@hazcod we just added a tag for v7.9.0, and plan to continue to make tags to accompany each stack release that contains rule changes. Can you confirm if you were subscribed to releases and got a notification?
