### ISSUE TITLE
Endpoint Security Not Working

### ISSUE THREAD

**Issue by Reda-BELHAJ** [elastic/detection-rules#1969]
Hey everyone,

I am using an agent that have a personalised policy with:

- Endpoint Security
- Windows
- System

And my issue is when I test a malicious behavior (with MITRE ATT&CK Techniques) I can't see the alerts and in my list of rules my endpoint security last response is a warning:

![image](https://user-images.githubusercontent.com/58605073/168480036-a147bb43-d4ce-4192-b388-8a15ee9682ee.png)

And the warning is:

> This rule is attempting to query data from Elasticsearch indices listed in the "Index pattern" section of the rule definition, however no index matching: ["logs-endpoint.alerts-*"] was found. This warning will continue to appear until a matching index is created or this rule is de-activated. If you have recently enrolled agents enabled with Endpoint Security through Fleet, this warning should stop once an alert is sent from an agent.

I also delete the integration (endpoint security) and add it again, but it didn't work.

So guys I'm here to express my issue and I really need your help.

Thank you
Reda BELHAJ

**Comment by w0rk3r** [comment]
Hey @Reda-BELHAJ, this warning message suggests that your endpoint hasn't sent any alert to your stack yet. That's why it doesn't exist; thus, the rule cannot run against it.

You can open a New Topic on the forum (https://discuss.elastic.co/) or join the #endpoint-security channel on the Slack Community Channel (https://ela.st/slack), so they can help you troubleshoot the issue.

Have a nice day ;)

**Comment by Reda-BELHAJ** [comment]
okay thank you @w0rk3r
