### ISSUE TITLE
[New Rule] GDrive Object Shared Publicly

### ISSUE THREAD

**Issue by randomuserid** [elastic/detection-rules#221]
## Description

Detect a GDrive file being shared publicly

## Required Info

- **Eventing Sources:**
filebeat

- **Platforms**
Gdocs

- **Target ECS Version:** 1.6
- **New fields required in ECS for this?**
- **Related issues or PRs**

## Optional Info
- **References:**

## Search Syntax
`gsuite.drive.visibility_change : * AND gsuite.drive.visibility: public_on_the_web`

**Comment by SHolzhauer** [comment]
Had a thought about this, within most organizations i know it's quite common for users to share documents outside of the organisation, usually through link sharing.

Basically I am struggling with the scale at which this rule seems usefull; 

* If you have a smaller organization it won't happen that often and analysts can look into it, however since its a smaller organization there most likely isn't a dedicated analyst.
* At larger organizations this event would trigger so often they can't all be investigated.
However, it's a valid tactic which has been observed before.

What are your thoughts on implementing this as a threshold rule?
For example if this event is seen 5 times (or more) in a 3 minute window.
