### ISSUE TITLE
[Rule Tuning] EQL bugs using regex and backslashes (Windows Paths)

### ISSUE THREAD

**Issue by w0rk3r** [elastic/detection-rules#2260]
## Rules affected

- https://github.com/elastic/detection-rules/blob/main/rules/windows/credential_access_cmdline_dump_tool.toml
- [Suspicious PowerShell Engine ImageLoad](https://github.com/elastic/detection-rules/blob/main/rules/windows/execution_suspicious_powershell_imgload.toml)
- [Image File Execution Options Injection](https://github.com/elastic/detection-rules/blob/main/rules/windows/persistence_evasion_registry_ifeo_injection.toml)

## Description

A [change](https://github.com/apache/lucene/commit/819e668ce2fcfcf86b652a191cdbe0fad0a8ffce#diff-93255512c837705492a154d5794b61f7132ae4264a292d224d5944de35f45847R1217) in Lucene seems to break the usage of `\` in regex conditions and [marked as a no-fix](https://github.com/elastic/sdh-security-team/issues/436#issuecomment-1222316011), so we need to adjust the logic of these rules accordindly. The impact is low, as these regex conditions are used as exceptions on our rules and not the main logic, but they can cause FPs.

The use of triple quotes seems to prevent the rule from throwing a error, but the regex will not working based on my testing.

[SDH](https://github.com/elastic/sdh-security-team/issues/436) issue for context.

**Comment by mark-dufresne** [comment]
@w0rk3r I had a question about the expected solution. Are you expecting to get rid of regex to work around for the bug/breaking change discussed in the SDH?

**Comment by w0rk3r** [comment]
Yeah, as it seems to be a no-fix, and our use here is to exclude paths, I'll replace the regex expressions with wildcards

**Comment by rw-access** [comment]
hello team! it's been a while [😉](https://emojipedia.org/winking-face/)
my understanding of what I can see publicly about that Lucene change is that it's actually a good thing! I wish it was done much earlier, to be honest. It removes leniency for `\` so that you can only use proper character escapes, and `\\` is valid but `\a` won't quietly become a literal `\` then `a` anymore.

As long as you use `\` properly and put it inside a `"""` it looks like it will work correctly. But there are a lot of issues here that are linked but not public so I can't grasp the full text. Everything I can see about `process.parent.executable regex~ """C:\\Program Files( \(x86\))?\\Cisco Systems\\.*"""` looks correct. The only slashes used there are used to escape special characters like `\`, `(` and `)`, so it looks like it would work as expected.

Is there any (public) documentation for how this breaks existing rules? All the existing rules should be using `\` properly like the above example, so I think you should be okay.

**Comment by brokensound77** [comment]
Thanks @rw-access, that sounds spot on!

I did a review of all existing rules using `regex` and I saw no issues. The only rule using regex which is _not_ triple quoted was ...., which has no escapes in the query

```sql
...
  winlog.event_data.AttributeValue regex~ "[0-9]{15}([1-9a-f]).*"
...
```

The original source of the issue was centered around custom rules, which were not triple quoting.

I think we can close #2284 with no further action beyond continuing to ensure proper syntax in our own rules

**Comment by w0rk3r** [comment]
Yeah, just validated our cases and seems there are really no issues on them (sorry and thanks!)... But the initial bug was something like this, but using single quotes:

Query:
```
process where
(
    process.name like "control.exe"
    and process.args like~ "*.cpl"
    and not process.command_line regex~ """.*:\\Windows\\System32\\\\w+\\.cpl.*"""
)
```

I suggested using triple quotes:

![image](https://user-images.githubusercontent.com/26856693/188251215-03376b65-9458-4d87-b833-cedf0fa00488.png)


Which doesn't throw any error, but doesn't match the condition neither:

![image](https://user-images.githubusercontent.com/26856693/188251115-2f5a4a3c-1d9e-4383-ae82-ab837d45fef3.png)

When I use a single backslach for `\w+` it throws this error:

```search_phase_execution_exception: [query_shard_exception] Reason: failed to create query: Query must not be null; [query_shard_exception] Reason: failed to create query: Query must not be null; [query_shard_exception] Reason: failed to create query: Query must not be null```

Any clues around this? It is really a bug?

**Comment by w0rk3r** [comment]
Yeah, just validated our cases and seems there are really no issues on them (sorry and thanks!)... But the initial bug was something like this, but using single quotes:

Query:
```
process where
(
    process.name like "control.exe"
    and process.args like~ "*.cpl"
    and not process.command_line regex~ """.*:\\Windows\\System32\\\\w+\\.cpl.*"""
)
```

I suggested using triple quotes:

![image](https://user-images.githubusercontent.com/26856693/188251215-03376b65-9458-4d87-b833-cedf0fa00488.png)


Which doesn't throw any error, but doesn't match the condition neither:

![image](https://user-images.githubusercontent.com/26856693/188251357-2913c622-8581-44e6-bc35-32934b3e6b36.png)

When I use a single backslach for `\w+` it throws this error:

```search_phase_execution_exception: [query_shard_exception] Reason: failed to create query: Query must not be null; [query_shard_exception] Reason: failed to create query: Query must not be null; [query_shard_exception] Reason: failed to create query: Query must not be null```

Any clues around this?

**Comment by rw-access** [comment]
not sure to be honest. it does look like you have `\\w` when you should have just `\w`.

also, keep in mind that it will have different results for different versions of Lucene because `\w` hasn't always been interpreted as a predefined character class, so for an old version it'll be the same as `\\w`. if you switch `\w` to `[a-z0-9_]` you'll get maximal compatibility!

you could also do `[^\\]` if you want to match all non-`\` characters so you get one directory

**Comment by w0rk3r** [comment]
I'm doing some more testing, and seems that the problem is that I can't use `\w+`, `\d+`, `\S+`, etc in 8+, not the backslashes:

In 8.3.3:
![image](https://user-images.githubusercontent.com/26856693/188432001-ec0072c0-fc44-44ca-a3f5-983f58d10870.png)

In 7.17.x it works just fine:
![image](https://user-images.githubusercontent.com/26856693/188433557-73e7f3b0-cbf2-4440-af25-36c079f8a91e.png)

Wdyt? @rw-access @brokensound77

**Comment by rw-access** [comment]
Personally, I would switch to `[a-z...]` style character classes for full compatibility. I don't know the best part forward for reporting, documentation, etc., so I'll let you all handle that.

**Comment by luigidellaquila** [comment]
I tested a similar query on a fresh 8.4.1 cloud instance and everything seems to work fine

<img width="1721" alt="Schermata 2022-09-13 alle 11 11 46" src="https://user-images.githubusercontent.com/459289/189862895-c531aba2-a941-4103-89ff-a258031c0905.png">

maybe I'm missing something, or the problem is already fixed in v 8.4.x... As far as I remember, we did not do much on these aspects recently, so if it's a fix, probably it's in Lucene.

**Comment by w0rk3r** [comment]
@luigidellaquila I just tested the following query in a new 8.4.1 and got the same error:

```
process where process.command_line regex~ """\w+"""
```

![image](https://user-images.githubusercontent.com/26856693/190155623-8e9e48cb-f7dc-4743-9637-ead1af5fb32b.png)

Diving a bit more, I just saw that it works normal with `process.args`:

![image](https://user-images.githubusercontent.com/26856693/190155916-37a0bc8a-9305-425e-bba8-eb0c9b538a9a.png)

Maybe this is a issue with wildcard fields?
![image](https://user-images.githubusercontent.com/26856693/190156830-53e10019-f986-465f-979c-1044343de8a9.png)

**Comment by luigidellaquila** [comment]
@w0rk3r I can confirm that the problem happens specifically on wildcard fields.
Actually, the problem is not strictly related to EQL, I tried to run a simple search query:

```
{
    "query": {
        "regexp": {
            "name": {
                "value": "\\w+"
            }
        }
    }
}
```

the query works fine if `name` is a `text` or a `keyword` field, but fails if it's a `wildcard`.

I think I found the problem in the code and a possible fix, I'll keep you updated

**Comment by luigidellaquila** [comment]
Hi all,

the PR with the fix was just merged on main branch (8.5)

**Comment by w0rk3r** [comment]
Awesome, I'll keep this one open until we have the BC for testing. @nastasha-solomon I think @luigidellaquila may give you a better picture of the bug/limitation to get https://github.com/elastic/security-docs/issues/2337 right, let me know if any input from my side is needed.

**Comment by w0rk3r** [comment]
Already worked with Nastasha and Luigi via Slack to get the bug properly documented, so I'm closing this as completed.
