### ISSUE TITLE
[Discuss] New Field Support Implementation Planning

### ISSUE THREAD

**Issue by eric-forte-elastic** [elastic/detection-rules#2479]
Related Issue: https://github.com/elastic/detection-rules/issues/2469

## Summary 
If we add new fields to the data section, we have to min stack again. Therefore we need to address how we handle new features to prevent from having to min stack all

**Comment by Mikaayenson** [comment]
## Update July 13th

Over the last several months we've added several controls within the detection-rules repo:

1. min_compat on some fields
2. Min stacked unit tests
3. build-limited-ndjson command and KB article for customers.
4. limited automated backporting
5. More validation for integrations, multi fields, etc.
6. 💡 TBD: We also need to add semantic versioning that aligns with specific rule changes (metadata, vs query changes). We need to plan with AET, as they cannot support semantic versioning at this time. 

However, the major concern is required fields that affect **_ALL_** rules since it affects back porting and versioning.

We still need from AET:
1. https://github.com/elastic/security-team/issues/6888
