### ISSUE TITLE
[Rule Tuning] Suspicious File Changes Activity Detected

### ISSUE THREAD

**Issue by BenB196** [elastic/detection-rules#3011]
## Link to rule

https://github.com/elastic/detection-rules/blob/e938ed28a046e0f85c63ac1c9592d472b6078e6c/rules/linux/impact_potential_linux_ransomware_file_encryption.toml#L21

## Description

In a large deployment, this rule never seems to complete successfully.

I believe the issue is a cardinality one, as:

https://github.com/elastic/detection-rules/blob/e938ed28a046e0f85c63ac1c9592d472b6078e6c/rules/linux/impact_potential_linux_ransomware_file_encryption.toml#L28

Seems extremely expensive.

## Example Data

![image](https://github.com/elastic/detection-rules/assets/8277432/fbe94dee-05e8-47cf-b032-008c23c83135)

![image](https://github.com/elastic/detection-rules/assets/8277432/0b6379af-709c-4a8f-b7b2-c6d3532c0606)

**Comment by Aegrah** [comment]
Hi @BenB196! Good catch. I changed the query in this [tuning PR](https://github.com/elastic/detection-rules/pull/3024). The `sequence by process.entity_id` is one of the most efficient/effective sequencing methods that we have, so changing this would most likely reduce the efficiency of the rule.

Instead, I chose to include a whitelist of processes and suspicious process executable locations, rather than using a blacklist tuning approach. This will not only increase the performance by a lot, but also decrease FPs in the process. In my testing stack, this query only requires about 25% of the time to run in comparison to the original rule. See the `[tuning 2]` rule. 

<img width="1226" alt="image" src="https://github.com/elastic/detection-rules/assets/78494512/a1112e4b-a051-4ccb-88ec-8a91bae5477a">

Would you mind giving this a try in your environment to see whether this tuning will suffice? 

Thanks for the suggestions, they are much appreciated!

**Comment by Aegrah** [comment]
Perfect, I'm glad to hear about that. When the PR mentioned above is merged, this issue will automatically be closed. You can also feel free to close it yourself if you feel like this tuning solved the issue.
