### ISSUE TITLE
[Bug] Fix Security Doc Generation for Special Characters in Rule Names and Deprecated Links

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/detection-rules#3032]
**Describe the bug**
When using the `release-docs` workflow in Detection Rules, security docs are generated and then a PR is opened to the Security Docs repo with the suggested changes reflecting rule changes.

1. When we have special characters in rule names such as `enumerating-domain-trusts-via-nltest.exe` they really need to be `enumerating-domain-trusts-via-nltest-exe`. This causes invalid references where ASCIIDOC's are unable to find necessary anchors.
2. When rules are deprecated, they are added to the rules package version index, but since the rule is deprecated, we remove the doc for that rule. This causes the links to break as the index is pointing to a doc that does not exist. We should always include this doc, but rather add a deprecation note to the top of it.

**Expected behavior**
1. Special characters should be replaced with `-` as we have done this historically.
2. Deprecated rules, although deprecated, should have their doc still created but rather updated with a `DEPRECATION` TAG.

**Screenshots**
Job reference: https://elasticsearch-ci.elastic.co/job/elastic+docs+pull-request+build/1660/console
<img width="1591" alt="Screenshot 2023-08-23 at 12 15 44 PM" src="https://github.com/elastic/detection-rules/assets/99630311/8caf9538-ce18-4113-911d-2d43e212062e">

<img width="721" alt="Screenshot 2023-08-23 at 12 15 59 PM" src="https://github.com/elastic/detection-rules/assets/99630311/a4d7a87e-c725-4c06-9f44-8dca0796d6bd">

<img width="707" alt="Screenshot 2023-08-23 at 12 16 05 PM" src="https://github.com/elastic/detection-rules/assets/99630311/456a2f09-b77b-4a72-a327-e166fcaf402c">

**Additional context**
This has caused an issue for the security docs team as shown in the following PR: https://github.com/elastic/docs/pull/2743

**Comment by lcawl** [comment]
I'm not sure if they're related to the same problem or not, but I've fixed more files in https://github.com/elastic/security-docs/pull/3811. If they're generated files, they'll likewise need a long-term fix.

**Comment by shashank-elastic** [comment]
#### Design For Missing Docs for Deprecated Rule

**Investigation** 

Looking at some old [PR](https://github.com/elastic/security-docs/pull/5033/commits/62e6570577e2440c1f7d30ec1854c289efa2a3c6#diff-01f4083fea809cb88d6668fb875161687bf215db800ac51c30c2459ea58f3b85) where we have had deprecated rules as a sample investigation point . 
- We have the appendix and the summary data populated 
- The prebuilt rule reference is missing aka, [this](https://www.elastic.co/guide/en/security/current/prebuilt-rules.html) needs to be populated 

**Bug : Why is this happening .**

1. Code Line [reference](https://github.com/elastic/detection-rules/blob/30ffe00012d8a6d7034011d48a7ca40c5910f8da/detection_rules/docs.py#L395) skips adding deprecated rules for rule details generation. 
2. Hence the Builds will have missing doc links and will fail, eventually prompting us to remove those links from summary and appendix 

**Requested Fix**

- We should always include this doc, but rather add a deprecation note to the top of it
- To achieve this we need to first get the prebuilt summary table populated [here](https://www.elastic.co/guide/en/security/current/prebuilt-rules.html)
- Remove the Skip criteria in code for generate_rule_reference and test to see if there are any failures. 
- Even before we try to get to populate, does it make sense from the product perspective to have a deprecated rule as part of the current structure. 
- The tabulations are  Rule | Description | Tags | Added | Version, but for a deprecated rule `Added` and `Version` does not make sense semantically 
- @approksiu What could be better recommendations here to handle this at the release updates phase. Since this is customer facing, my best bet was to run this through you, with couple of Q(s)
    -- If we plan to include deprecated rule docs does it make sense to add it in prebuilt rule reference. If we dont wanna add it all thogether, the fix would be to stop populating appendix and the summary data for deprecated rules. Currently we manually remove them as show in above PR(s)
     -- We plan to include them but have a varied structure, what could be suggested here, as practise to follow. Say may be one possibility is to include a note of deprecated rules in Summary [page](https://www.elastic.co/guide/en/security/current/prebuilt-rule-8-14-5-prebuilt-rules-8-14-5-summary.html) without rule links,  like a note or a list of rule criteria. [ This may not fly but a strange possibility ]

@Mikaayenson / @terrancedejesus thoughts and comments initially before we open this up for review from the team.

**Comment by shashank-elastic** [comment]
#### Design When we have special characters in rule names

Investigation

- Run the  name_to_title [function](https://github.com/elastic/detection-rules/blob/main/detection_rules/docs.py#L644) that is responsible for generating titles locally with the exception names. 

```console
>>> name="Enumerating Domain Trusts via DSQUERY.EXE"
>>> initial = re.sub(r'[^\w]|_', r'-', name.lower().strip())
>>> final = re.sub(r'-{2,}', '-', initial).strip('-')
>>> print(final)
enumerating-domain-trusts-via-dsquery-exe
>>> ```

- There looks to be no fault in regex at this time as the function is replacing the name of the rule in the expected format. 
- There will be no fix for this @terrancedejesus

**Comment by shashank-elastic** [comment]
For `Design For Missing Docs for Deprecated Rule` 

This was discussed with @approksiu and the following was discussed. 

- We will gather details if the deprecated rule will receive update that it is deprecated.
   - Which we feel that the packaging as of today does not include deprecated rules , looking at the past release history

Then the suggested approach is
- We could announce rule deprecation to users and then. remove the rules in the next release.
- The Question is around edge cases of what happens if user is not on latest and skip certain rule updates --> fOr @approksiu 
- Figuring these steps we will come back to understand how documentation supports this.

**Comment by shashank-elastic** [comment]
Pinning the Rule Deprecation Doc for reference - https://docs.google.com/document/d/1eRyzG7rGNLrPKTHYHP8M1qRBlBrL0QzLwOx2x5ypg2w/edit

**Comment by shashank-elastic** [comment]
While this issue has historical context of 2 issues 
- Generate Docs for Deprecated Rules
- Allow special characters in rule names 

The issue of `Allow special characters in rule names` is already fixed as investigated in [comment](https://github.com/elastic/detection-rules/issues/3032#issuecomment-2203961260).

With some discussions of how do we plan to present docs for deprecated rules this turned into a dedicated feature request as such and is now being tracked for Q2 in https://github.com/elastic/detection-rules/issues/3897. 

We will be moving the discussions and implementation to the new issue @approksiu 

cc @Mikaayenson Closing this one!
