### ISSUE TITLE
[Rule Tuning] Abnormal Process ID or Lock File Created

### ISSUE THREAD

**Issue by BenB196** [elastic/detection-rules#3041]
## Link to rule

https://github.com/elastic/detection-rules/blob/main/rules/linux/execution_abnormal_process_id_file_created.toml

## Description

Related to: https://github.com/elastic/detection-rules/issues/2979

After upgrading to the latest release of this rule; https://github.com/elastic/detection-rules/pull/2985, I'm still seeing it timing out on a large deployment.

![image](https://github.com/elastic/detection-rules/assets/8277432/ee5eaa70-92b4-4fc2-affe-38c3eddb8258)

Based on the previous thread, I'm not 100% sure what the best "solution" for this rule is to fix its long query times.

**Comment by BenB196** [comment]
Just an additional note, I saw that this rule received some additional changes as part of https://github.com/elastic/detection-rules/pull/3024, so I went ahead and test these changes, however, I still observed the rule timing out on this latest set of tuning.

**Comment by Aegrah** [comment]
Hi @BenB196 Because the previous tuning apparently didn't do the job, I did a remake of the rule [here](https://github.com/elastic/detection-rules/pull/3058). Would you mind testing this new logic in your environment to see whether it successfully runs? In my environment this is much more efficient, so I think it should be good. 

Thanks for the suggestion as always!

**Comment by BenB196** [comment]
Hi @Aegrah,

I was able to test this, but unfortunately, I'm still seeing this time out.

![image](https://github.com/elastic/detection-rules/assets/8277432/291e9049-c570-4153-bc16-b3133f1bb8b3)


Screenshot of the rule:

![image](https://github.com/elastic/detection-rules/assets/8277432/cdca68b1-d585-4073-b64f-77de01b33a54)
