### ISSUE TITLE
[FR] Better way to work with non-ecs fields

### ISSUE THREAD

**Issue by stevengoossensB** [elastic/detection-rules#3262]
I'm always frustrated when we use a non-ecs field in our custom rules and I need to manually update the non-ecs-schema.json to include that field.

I would like a possibility to add a field with all of it's subfields, or even a full index to the schema, so the fields don't get checked for ECS compliance, so we can exclude certain indices from ECS validation or put all non-ecs fields as subfields to one field.

**Comment by Mikaayenson** [comment]
👋 Hey @stevengoossensB we hear you! We started reviewing this file a while back in (see https://github.com/elastic/detection-rules/issues/1776 for context). TLDR; The main issue at the time was integration fields sometimes changed between stack versions, and since we backport, forcing us to use this file in some cases. 

We also explored migrating these fields to the integrations themselves (by opening PRs, e.g. https://github.com/elastic/integrations/pull/5115), which still is a good idea long term (given the fields match older stacks that we support).  

Can you provide an example field your missing and the full index to the schema? The other options you mentioned may be viable options to solve your issue with subfields.

**Comment by stevengoossensB** [comment]
In my concrete example, I had to add panw.panos.action in the logs-panw.panos-*, but I expect this issue could pop up everywhere in the future.

Maybe there should be an option to be a bit more relax on the ECS compliance, as in customer environments, there's much more data sources that are not using integrations or are not fully ECS compliant, which hinders from using the rest of the tool for validation and deployment.

**Comment by stevengoossensB** [comment]
Bypass would work, skipping that validation, or returning warnings rather then errors (it is still good to know where we are not ECS compliant and where we could improve in the future).

**Comment by slawomirbabicz** [comment]
What I am doing personally as a hack is:

1). Created file: non-ecs-schema_extension.json

```
{ 
  "logs*": {
      "github.repo": "keyword",
      "github.org": "keyword",
      "github.repository_public": "boolean",
      "github.category": "keyword",
      "github.permission": "keyword",
      "json.action.type": "keyword"
  }
}
```

2). I am appending that file to: `/detection-rules/detection_rules/etc/non-ecs-schema.json`

**Comment by stevengoossensB** [comment]
I'm doing something similar, by overwriting the **non-ecs-schema.json** file with my own version. However, in an environment with plenty of index patterns, different custom data sources, custom fields that are used in multiple index patterns,... It becomes a bit of a mess.

Maybe there could be a way to just add the exception filed names, regardless of the index, to a list (by specifying them in the * index?)

**Comment by eric-forte-elastic** [comment]
This will be addressed through the DAC feature branch issue https://github.com/elastic/detection-rules/issues/3618.

**Comment by eric-forte-elastic** [comment]
With the new feature from https://github.com/elastic/detection-rules/pull/3889, we now support custom shemas and the auto generation of custom schemas (see A11 from our [FAQ](https://dac-reference.readthedocs.io/en/latest/faq.html) for an example). If you run into any issues with custom schemas or auto generation please feel free to re-open this issue or create a new one.
