### ISSUE TITLE
[FR][DAC] further decouple reliance on default rule dir locations

### ISSUE THREAD

**Issue by brokensound77** [elastic/detection-rules#3619]
Note: this work will target the [DAC-feature](https://github.com/elastic/detection-rules/tree/DAC-feature) branch

related to https://github.com/elastic/detection-rules/pull/3407

---

These global constants:

https://github.com/elastic/detection-rules/blob/303a64e388bdd7684ee654a4a48ebd19a9934e3a/detection_rules/rule_loader.py#L27-L30

Need to be revised to fully adopt the portable approach introduced by #3407 (using `RULES_CONFIG.*`).

However, the use of these variables is not consistently just for rule loading, and they have several hardcoded dependencies on them, so they cannot simply be replaced.

<img width="742" alt="image" src="https://github.com/elastic/detection-rules/assets/16747370/b47d8479-58f8-4494-a488-4b1721b6fdc2">

**Comment by eric-forte-elastic** [comment]
Additional Considerations:
- This PR should make BBR rules directories optional
- In the config, we should have a separate path list for BBR rules dirs as they are handled differently
- In the config, we should also have an RTA section (expected to be optional as well)
- Need to update the current loading of rules to support a list of paths to be loaded, instead of one.

**Comment by eric-forte-elastic** [comment]
PR is merged, this issue is now complete.
