### ISSUE TITLE
[Rule Tuning] Review timeline templates per rules

### ISSUE THREAD

**Issue by brokensound77** [elastic/detection-rules#453]
## Description
As noted [here](https://github.com/elastic/kibana/pull/82214#pullrequestreview-522151107), some of the timeline templates could be better revised for some of the rules. Potentially adding new templates for certain rule types as well

**Comment by XavierM** [comment]
I would like to offer an idea, I think we should re-visit our tags for rules and add some for timeline since Kibana added global tags with this [PR](https://github.com/elastic/kibana/pull/79096). If we do that instead to only have one template timeline link to a rule, we can have multiple template timeline link to a rule if we associate them by tags. Therefore, the user will be able to investigate an alert by multiple template timeline who match a rule's tags (meaning that you will have a dropdown of template timeline if tags match). I feel like this way the user will be able to open the timeline in multiple contexts.

**Comment by MikePaquette** [comment]
@XavierM I think this is a great idea.  The analyst experience of being able to "try" a few different templates when investigating an alert is something we've heard requested as an enhancement.  

When would the tag matching be performed?  After the click on "Investigate in Timeline?"  

If so, this would mean that we could add a new timeline template asynchronously, and w/o editing the rule, analysts could access the new template if its tag matched the tag specified in the rule?  That would be a big win for users and for our rules development.

cc: @shimonmodi @paulewing @cosiomoises

**Comment by XavierM** [comment]
> @XavierM I think this is a great idea. The analyst experience of being able to "try" a few different templates when investigating an alert is something we've heard requested as an enhancement.
> 
> When would the tag matching be performed? After the click on "Investigate in Timeline?"
>

I was thinking that just after ![image](https://user-images.githubusercontent.com/189600/98132912-f2a2ae80-1e8a-11eb-90cf-ebb40c9876db.png) will add this icon ![image](https://user-images.githubusercontent.com/189600/98133000-0c43f600-1e8b-11eb-9808-cec3b43ba79e.png) so you can open more template timelines associated with the rules

> 
> If so, this would mean that we could add a new timeline template asynchronously, and w/o editing the rule, analysts could access the new template if its tag matched the tag specified in the rule? That would be a big win for users and for our rules development.
>

 Yes, we will simplify that flow, and the next step will be doing the same thing with Cases. Therefore these tags are becoming meaningful through our solution ❤️

**Comment by shimonmodi** [comment]
Let's also add telemetry to track timeline template usage - how many times is each template used, and how many rules have templates associated with them.
