### ISSUE TITLE
[Bug] Trojan detected in /rta/bin/Installer.msi

### ISSUE THREAD

**Issue by dovmor** [elastic/detection-rules#56]
**Describe the bug**
A Win32/Occamy.AA torojan is detected in the /rta/bin/Installer.msi file when scanning with Microsoft  AV.

**To Reproduce**
1. download the installer.msi file 
2. scan with Microsoft defender antivirus  
4. See the alert. 

**Screenshots**
![image](https://user-images.githubusercontent.com/17484850/87399165-a40d9380-c5bf-11ea-8acf-1fae57ed9e5d.png)

**Comment by rw-access** [comment]
hello @dovmor!
this is a custom file that we built, and we think that it's flagging because of `myapp.exe`. I think `myapp.exe` has since been marked as benign. We reached out to MS and I believe they've double checked and updated their definitions.

Can you update your AV definitions and let us know if it still flags?

**Comment by rw-access** [comment]
I'm going to close this issue. If you see that it still flags, please feel free to reopen.
