### ISSUE TITLE
[New Rule] Attempts to Brute Force an O365 User Account

### ISSUE THREAD

**Issue by bm11100** [elastic/detection-rules#568]
## Description
Identifies attempts to brute force an O365 user account. An adversary may attempt a brute force or password spraying attack to obtain unauthorized access to user accounts. 

This will be a threshold rule type that aggregates events by the O365 user id value (user.id) with a count of 10 and a lookback value of TBD minutes.

## Required Info

- **Eventing Sources:**
`filebeat-*`

- **Platforms**
`o365`

- **Target ECS Version:** `1.0.6`
- **New fields required in ECS for this?**
- **Related issues or PRs**

## Optional Info
- **References:**

## Example Logic
```
event.dataset:o365.audit and event.provider:AzureActiveDirectory and event.category:authentication and event.action:UserLoginFailed and event.outcome:failure
```
## Screenshot 
![image](https://user-images.githubusercontent.com/56412096/99450716-1df7b580-28ef-11eb-84a2-795cd605ca53.png)

**Comment by willemdh** [comment]
@bm11100 Good idea, but in my experience these kind of rules generate a lot of noise, becasue users tend to mistype / forget their password etc. (actually people resetting their password and then forgetting to update the settings on their mobile is the most frequent reason)

Would an EQL rule maybe more suitable which could only trigger if 2 or more failed authentications are detected by user?

Instead of:

`event.dataset:o365.audit and event.provider:AzureActiveDirectory and event.category:authentication and event.action:UserLoginFailed and event.outcome:failure`

```
sequence by user.name with maxspan=15m
      [ authentication where event.dataset:o365.audit and event.provider:AzureActiveDirectory and event.action:"UserLoginFailed" ]
      [ authentication where event.dataset:o365.audit and event.provider:AzureActiveDirectory and event.action:"UserLoginFailed" ]
```

Grtz

Willem

**Comment by bm11100** [comment]
Hey @willemdh! Thanks for the suggestion! I noted in the description, but this is actually going to be a threshold rule type. I haven't decided on the threshold yet, but potentially say 10 failures in 5m for example. The threshold value and timeframe will just be in a different section in the metadata, so the query does look like it's just looking for a single login failure now, but that won't be the case once the rule is finalized. I do agree, looking for single login failures or even a few, based on potential password expirations would be pretty noisy.

**Comment by willemdh** [comment]
@bm11100 Thanks for the suggestion, I updated my "Elastic Auditing - Authentication Failed" to also use the threshold rule type. 👍🏻

![image](https://user-images.githubusercontent.com/6462991/100098567-83532580-2e5e-11eb-877d-3bf4f5a1bfe9.png)

Only very recently updated to 7.10 and didn't realise the threshold rule type was also added.
